services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    buildCommand: npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://fenmo-expense-tracker-frontend-q83u.onrender.com

  - type: static
    name: expense-tracker-frontend
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://expense-tracker-backend-9f2h.onrender.com
      - key: BUILD_TIMESTAMP
        value: "2026-04-30-force-redeploy"
